### PR TITLE
Remove RCS headers

### PR DESCRIPTION
**Pull request by ThexXTURBOXx**
This was done semi-automatically using a script that I wrote in Java.
I am still able to compile everything, so I guess everything has worked fine.
The RCS log is probably unnecessary now as you have successfully migrated to Git - but think of this PR as "optional" anyway. If you prefer to keep the RCS logs, just ignore or close this PR.

### CODE REVIEW

**Comment by JohnAAbbott** [comment]
Thnaks, Nico.  I think this is probably a god idea, but I'd like to discuss with @annabigatti before merging.  The only real question is whether we might be discarding any "useful historical information" -- TBH I hardly ever look through those change-log lines...

**Comment by annabigatti** [comment]
Hi Nico, it's my fault, I'm paranoid and very fond of those logs.   
But you are right, and we should just keep our last version with logs safe and aside,  and clear the logs off in git.
But just because I'm paranoid, and I would like to check before committing ;-)  would it be hard for you to split this pull-request into separate ones, for example one per directory?  (so I can check and merge one block at a time?) 
I'm not sure I explained this idea clearly enough (and I'm still getting used to git)

**Comment by ThexXTURBOXx** [comment]
Hi Anna! That's really no problem! And yes, usually I am also rather paranoid about stuff like this; so I completely understand.
I will try to split this PR into multiple smaller ones hopefully during this weekend at some point :-)

**Comment by ThexXTURBOXx** [comment]
Split this into 5 smaller PRs. Will close this as merging all of them is equivalent to merging this single one!

**Pull request closed without merging**
